# _config.yml

# Site Settings
title: NLP with Cloud Tools - Course Materials
description: "Outline, resources, and materials for the NLP with Cloud Tools class."

# Theme Selection
theme: jekyll-theme-primer # Or choose another supported theme

# Optional: Add Google Analytics ID if you use it
# google_analytics: UA-XXXXXXXXX-X 